function tfInit(name)

% initialize TikZ figure
%
% tfInit
% tfInit(name)
%
% name: identifier of the figure window used for preview, and basis of the
%       name of the file generated by tfRender
%
% If no name is specified, it is attempted to construct one from the name
% of the calling script or function.


% determine name
if nargin == 0
    [ST,I] = dbstack;
    if size(ST, 1) < I + 1
        error('Cannot determine name of figure!')
    end
    [~, name] = fileparts(ST(I + 1).name);
end

% check
if ~isempty(intersect(name, ' '))
    error('Invalid figure name "%s"!', name)
end

fprintf('tfInit %s\n', name)

% manage figure window
try close(name), catch, end
figure
set(gcf, 'Name', name)

% initialize TikZ-LaTeX code
tf_set('code', {});

% prepare temporary directory
temp = tempname;
mkdir(temp)
tf_set('temp', temp)
